import { Card, CardContent } from "@/components/ui/card"
import { Navbar } from "@/components/layout/Navbar"
import Head from "next/head"
import { Footer } from "@/components/layout/Footer"

export default function TermsOfServicePage() {
  return (
    <>
      <Head>
        <title>Terms of Service - Instagen</title>
        <meta name="description" content="Terms of Service for Instagen, a platform for creating virtual influencers" />
      </Head>
      
      <Navbar />
      <main className="pt-24 min-h-screen bg-gradient-to-b from-background to-background/95">
        <div className="container py-12">
          <Card className="mx-auto max-w-4xl">
            <CardContent className="p-8">
              <h1 className="text-3xl font-bold text-center mb-8">Terms of Service - Instagen</h1>
              
              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">Service Overview</h2>
                <p className="text-muted-foreground">
                  Instagen is a SaaS platform that allows users to easily create realistic virtual influencers using artificial intelligence technologies.
                </p>
              </section>

              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">Acceptance of Terms</h2>
                <p className="text-muted-foreground">
                  By using the Instagen service, you fully and unreservedly accept these terms of service.
                </p>
              </section>

              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">Account Creation and Personal Data</h2>
                <p className="text-muted-foreground">
                  To access the service, you must create an account by providing your email address. You are responsible for maintaining the confidentiality of your credentials.
                </p>
              </section>

              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">Use of Generated Content</h2>
                <p className="text-muted-foreground">
                  You are authorized to freely use content generated by Instagen for commercial or non-commercial purposes, without specific limitation. However, you assume full legal responsibility related to your use of this content.
                </p>
              </section>

              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">User Responsibility</h2>
                <p className="text-muted-foreground">
                  You agree not to create content that is illegal, defamatory, discriminatory, violent, or infringes on third-party rights. Instagen disclaims all responsibility regarding content created by its users.
                </p>
              </section>

              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">Limitation of Liability</h2>
                <p className="text-muted-foreground">
                  Instagen provides a technological tool and cannot be held responsible for the direct or indirect consequences of using content created via the platform. You expressly release Instagen from any liability related to your activities and your uses of generated content.
                </p>
              </section>

              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">Intellectual Property</h2>
                <p className="text-muted-foreground">
                  Instagen remains the exclusive owner of the technology, codes, and algorithms that make up the service. You agree to respect this intellectual property and not attempt to copy, modify, or distribute the Instagen service or its technical elements.
                </p>
              </section>

              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">Modification of Terms</h2>
                <p className="text-muted-foreground">
                  Instagen reserves the right to modify these terms of service at any time. Any modification will take effect immediately upon publication on this page.
                </p>
              </section>

              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">Applicable Law</h2>
                <p className="text-muted-foreground">
                  These terms are governed by and interpreted in accordance with French law. In the event of a dispute, the French courts shall have exclusive jurisdiction.
                </p>
              </section>

              <section className="mb-6">
                <h2 className="text-xl font-semibold text-primary mb-2">Contact</h2>
                <p className="text-muted-foreground">
                  For any questions regarding these terms of service, you can contact us at:{' '}
                  <a href="mailto:support@instagen.ai" className="text-primary hover:underline">
                    support@instagen.ai
                  </a>
                </p>
              </section>
              
              <div className="mt-10 pt-6 border-t text-center text-sm text-muted-foreground">
                &copy; {new Date().getFullYear()} Instagen. All rights reserved.
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <Footer />
    </>
  )
} 